config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }
  devise_for :end_users, controllers: {
  sessions:      'publics/sessions',
  passwords:     'publics/passwords',
  registrations: 'publics/registrations'
  }

  scope module: :publics do
    resources :places, only: [:create,:destroy,:show,:edit,:update,:delete]
    patch 'end_users/withdrawal' =>'end_users#withdrawal'
    get 'end_users/mypage' => 'end_users#show'
    get 'end_users/information/edit' => 'end_users#edit'
    patch 'end_users/infomation' => 'end_users#update'
    root 'homes#top'
    resources :groups, only: [:new,:index,:show,:edit,:create]
    post 'groups/add_user' => 'groups#add_user'
    get 'end_users/confirm' => 'end_users#confirm'
    resources :group_users, only:[:destroy]
    # create 'customers/customers/infomation' => 'customers#update'
  end

  namespace :admins do
    resources :end_users, only: [:index,:show,:edit,:update]
    resources :groups, only: [:index,:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
  # mount_uploader :image, ImageUploader
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :places

  # validates :name, presence: true
  # validates :introduction, presence: true
  # validates :image_id, presence: true
  # validates :is_deleted, presence: true
  validates :email, presence: true
end

app/controllers/admins/end_users_controller.rb
class Admins::EndUsersController < ApplicationController
  def index
    @end_users = EndUser.all
  end

  def show
    @end_user = EndUser.find(params[:id])
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    @end_user = EndUser.find(params[:id])
    if @end_user.update(end_user_params)
      redirect_to admins_end_user_path(@end_user)
    else render:edit
    end
  end

  private

  def end_user_params
    params.require(:end_user).permit(:name,:image,:introduction,:email,:is_deleted)
  end
end

app/controllers/publics/end_users_controller.rb
class Publics::EndUsersController < ApplicationController
  def show
    @end_user = current_end_user
  end

  def edit
    @end_user = current_end_user
  end

  def update
    @end_user = EndUser.find(current_end_user.id)
    @end_user.update(end_user_params)
    redirect_to end_users_mypage_path(@end_user)
  end

  def confirm
  end

  def withdrawal
    @end_user = EndUser.find(current_end_user.id)
    @end_user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def end_user_params
    params.require(:end_user).permit(:name,:image,:introduction,:email,:is_deleted)
  end
end

app/helpers/admins/end_users_helper.rb
module Admins::EndUsersHelper
end

app/helpers/publics/end_users_helper.rb
module Publics::EndUsersHelper
end

app/views/admins/end_users/edit.html.erb
<% if @end_user.errors.any? %>
  <%= @end_user.errors.count %>件のエラーが発生しました
  <% @end_user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="row">
  <div class="col-auto offset-2 mt-5">
    <h2>会員編集</h2>
  </div>
</div>
<%= form_with model: @end_user, url: admins_end_user_path(@end_user), method: :PATCH, local:true do |f| %>
  <div class="row mt-5">
    <div class="col-2 offset-3">
      <h5>プロフィールアイコン</h5>
    </div>
    <div class="col-3">
      <%= f.attachment_field :image %>
      <%#= f.file_field :image %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-2 offset-3">
      <h5>ニックネーム</h5>
    </div>
    <div class="col-3">
      <%= f.text_field :name,class: 'form-control',autofocus: true, autocomplete: "name" %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-2 offset-3">
      <h5>自己紹介</h5>
    </div>
    <div class="col-3">
      <%= f.text_area :introduction,class: 'form-control',autofocus: true, autocomplete: "introduction" %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-2 offset-3">
      <h5>メールアドレス</h5>
    </div>
    <div class="col-3">
      <%= f.text_field :email,class: 'form-control',autofocus: true, autocomplete: "email" %>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-2 offset-3">
      <h5>会員ステータス</h5>
    </div>
    <div class="col-auto">
      <%= f.radio_button :is_deleted, false %>
      <%= f.label :is_deleted, "有効" %>
    </div>
    <div class="col-auto">
      <%= f.radio_button :is_deleted, true %>
      <%= f.label :is_deleted, "退会" %>
    </div>
  </div>
  <div class="row pb-5">
    <div class="col-2 mx-auto mt-5">
      <%= f.submit "マイページ変更", class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<%end%>

app/views/admins/end_users/index.html.erb
<div class="row">
  <div class="col-auto offset-2 mt-5">
    <h2>会員一覧</h2>
  </div>
</div>
<div class="row mt-5 mb-5">
  <div class="col-8 mx-auto">
    <table class="table table-bordered border-dark">
      <thead>
        <tr>
          <th class="col-4">会員名</th>
          <th class="col-5">会員紹介</th>
          <th class="col-3"></th>
        </tr>
      </thead>
      <tbody>
        <% @end_users.each do |end_user| %>
          <tr>
            <td>
              <%= attachment_image_tag end_user, :image, size: "30x20", format: 'jpeg' %>  <%= end_user.name %>
            </td>
            <td>
              <%= end_user.introduction %>
            </td>
            <td>
              <div class="row">
                <div class="col-auto mx-auto">
                  <%= link_to admins_end_user_path(end_user) do %>
                    <button type="button" class="btn btn-primary">会員詳細</button>
                  <%end%>
                </div>
              </div>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/admins/end_users/show.html.erb
<div class="row">
  <div class="col-auto offset-2 mt-5">
    <h2>会員詳細</h2>
  </div>
</div>
<div class="row mt-5">
  <div class="col-2 offset-3">
    <h5>プロフィールアイコン</h5>
  </div>
  <div class="col-3">
    <% if @end_user.image.blank? %>
    　<%= image_tag '/images/default.png' %>
    <%else%>
      <%= attachment_image_tag @end_user, :image, size: "300x200", format: 'jpeg' %>
    <% end %>
  </div>
</div>
<div class="row mt-5">
  <div class="col-2 offset-3">
    <h5>ニックネーム</h5>
  </div>
  <div class="col-3">
    <%= @end_user.name %>
  </div>
</div>
<div class="row mt-5">
  <div class="col-2 offset-3">
    <h5>自己紹介</h5>
  </div>
  <div class="col-3">
    <%= @end_user.introduction %>
  </div>
</div>

<div class="row mt-5">
  <div class="col-2 offset-3">
    <h5>メールアドレス</h5>
  </div>
  <div class="col-3">
    <%= @end_user.email %>
  </div>
</div>
<div class="row mt-5">
  <div class="col-2 offset-3">
    <h5>会員ステータス</h5>
  </div>
  <div class="col-3">
    <% if @end_user.is_deleted == false then %>
      <h6 class="my-auto text-success">有効</h6>
    <%else%>
      <h6 class="my-auto text-dark-50">無効</h6>
    <%end%>
   </div>
</div>

<div class="row mt-5 pb-5">
  <div class="col-2 offset-3">
    <h5>マイページ編集</h5>
  </div>
  <div class="col-3">
    <%= link_to edit_admins_end_user_path(@end_user) do %>
      <button type="button" class="btn btn-secondary btn-block">会員編集</button>
    <%end%>
  </div>
</div>