config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }
  devise_for :end_users, controllers: {
  sessions:      'publics/sessions',
  passwords:     'publics/passwords',
  registrations: 'publics/registrations'
  }

  scope module: :publics do
    resources :places, only: [:create,:destroy,:show,:edit,:update,:delete]
    patch 'end_users/withdrawal' =>'end_users#withdrawal'
    get 'end_users/mypage' => 'end_users#show'
    get 'end_users/information/edit' => 'end_users#edit'
    patch 'end_users/infomation' => 'end_users#update'
    root 'homes#top'
    resources :groups, only: [:new,:index,:show,:edit,:create]
    post 'groups/add_user' => 'groups#add_user'
    get 'end_users/confirm' => 'end_users#confirm'
    resources :group_users, only:[:destroy]
    # create 'customers/customers/infomation' => 'customers#update'
  end

  namespace :admins do
    resources :end_users, only: [:index,:show,:edit,:update]
    resources :groups, only: [:index,:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
  # mount_uploader :image, ImageUploader
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :places

  # validates :name, presence: true
  # validates :introduction, presence: true
  # validates :image_id, presence: true
  # validates :is_deleted, presence: true
  validates :email, presence: true
end

app/controllers/admins/end_users_controller.rb
class Admins::EndUsersController < ApplicationController
  def index
    @end_users = EndUser.all
  end

  def show
    @end_user = EndUser.find(params[:id])
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    @end_user = EndUser.find(params[:id])
    if @end_user.update(end_user_params)
      redirect_to admins_end_user_path(@end_user)
    else render:edit
    end
  end

  private

  def end_user_params
    params.require(:end_user).permit(:name,:image,:introduction,:email,:is_deleted)
  end
end

app/controllers/publics/confirmations_controller.rb
# frozen_string_literal: true

class Publics::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/publics/end_users_controller.rb
class Publics::EndUsersController < ApplicationController
  def show
    @end_user = current_end_user
  end

  def edit
    @end_user = current_end_user
  end

  def update
    @end_user = EndUser.find(current_end_user.id)
    @end_user.update(end_user_params)
    redirect_to end_users_mypage_path(@end_user)
  end

  def confirm
  end

  def withdrawal
    @end_user = EndUser.find(current_end_user.id)
    @end_user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def end_user_params
    params.require(:end_user).permit(:name,:image,:introduction,:email,:is_deleted)
  end
end

app/controllers/publics/group_users_controller.rb
class Publics::GroupUsersController < ApplicationController
  def destroy
    @group = Group.find(params[:id])
    @end_user = current_end_user
    @group.end_users.delete(current_end_user)
    redirect_to groups_path
  end
end

app/controllers/publics/groups_controller.rb
class Publics::GroupsController < ApplicationController
  def new
    @group = Group.new
  end
  def show
    @group = Group.find(params[:id])
    @place = Place.new
  end

  def index
    @end_user_group_all = current_end_user.groups
    @group_user = GroupUser.new
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    if @group.save
       @group.end_users << current_end_user
      redirect_to group_path(@group), notice: 'グループを作成しました'
    else
      render:new
    end
  end

  def add_user
    @group = Group.find(params[:group_user][:group_id])
    end_user = EndUser.find(params[:group_user][:end_user_id])
    @group.end_users << end_user
    redirect_to group_path(@group), notice: "ユーザーを追加しました。"
  end

  private

  def group_params
    params.require(:group).permit(:name,:introduction,:image,:is_open,:group_id,:end_user_id)
  end
end

app/controllers/publics/homes_controller.rb
class Publics::HomesController < ApplicationController
  def top
  end
end

app/controllers/publics/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Publics::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/publics/passwords_controller.rb
# frozen_string_literal: true

class Publics::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/publics/places_controller.rb
class Publics::PlacesController < ApplicationController
  skip_forgery_protection only: :create
  def create
    @group = Group.find(params[:place][:group_id])
    @place = Place.new(place_params)
    if @place.save
      redirect_to group_path(@group)
    else
      render "publics/groups/show"
    end
  end

  def show
    @place = Place.find(params[:id])
    @group = @place.group_id
  end
  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])
    if @place.update(place_params)
      redirect_to place_path(@place)
    else
      render :edit
    end
  end

  def destroy
    place = Place.find(params[:id])
    group = place.group_id
    place.destroy
    redirect_to group_path(group)
  end

  private
  def place_params
    params.require(:place).permit(:end_user_id, :group_id, :place_name,:address,:introduction,:latitude,:longitude,:image,:number)
  end
end

app/controllers/publics/registrations_controller.rb
# frozen_string_literal: true

class Publics::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  def after_sign_up_path_for(resource)
    end_users_mypage_path
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/publics/sessions_controller.rb
# frozen_string_literal: true

class Publics::SessionsController < Devise::SessionsController

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    test = EndUser.where(email: end_user_params[:email])
    if end_user_params[:email].blank?
      redirect_to new_end_user_session_path, notice: '登録してあるメールアドレスを入力してください'
    elsif end_user_params[:password].blank?
      redirect_to new_end_user_session_path, notice: '登録してあるパスワードを入力してください'
    elsif test[0][:is_deleted] == false
      super
    else
      redirect_to new_end_user_session_path, notice: '退会したアカウントではログインできません'
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(resource)
    end_users_mypage_path
  end

  # protected
  private
    def end_user_params
      params.require(:end_user).permit(:email,:password)
    end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/publics/unlocks_controller.rb
# frozen_string_literal: true

class Publics::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/end_users_helper.rb
module Admins::EndUsersHelper
end

app/helpers/publics/end_users_helper.rb
module Publics::EndUsersHelper
end

app/helpers/publics/group_users_helper.rb
module Publics::GroupUsersHelper
end

app/helpers/publics/groups_helper.rb
module Publics::GroupsHelper
end

app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

app/helpers/publics/places_helper.rb
module Publics::PlacesHelper
end

app/views/publics/end_users/confirm.html.erb
<div class="row mt-5">
  <div class="col">
    <h4 class="text-center">本当に退会しますか？</h5>
  </div>
</div>

<div class="row mt-5">
  <div class="col">
    <h5 class="text-center">
      退会すると、会員登録情報や<br>
      参加しているグループが閲覧できなくなります。<br>
      退会する場合は、「退会する」をクリックしてください
    </h5>
  </div>
</div>
<div class="row  justify-content-md-center mt-5 marginbottom">
  <div class="col-2">
    <%= link_to end_users_mypage_path do %>
      <button type="button" class="btn btn-primary btn-block">退会しない</button>
    <%end%>
  </div>
  <div class="col-2">
    <%= link_to "退会する",end_users_withdrawal_path, class: "btn btn-block btn-danger", method: :PATCH, data: {confirm: "退会しますか？"} %>
  </div>
</div>

app/views/publics/end_users/edit.html.erb
<div class="row">
  <div class="col-auto offset-2 mt-5">
    <h2>マイページ編集</h2>
  </div>
</div>
<%= form_with model: @end_user, url: end_users_infomation_path(@end_user), local:true do |f| %>
  <div class="row mt-5">
    <div class="col-2 offset-3">
      <h5>プロフィールアイコン</h5>
    </div>
    <div class="col-3">
      <%= f.attachment_field :image %>
      <%#= f.file_field :image %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-2 offset-3">
      <h5>ニックネーム</h5>
    </div>
    <div class="col-3">
      <%= f.text_field :name,class: 'form-control',autofocus: true, autocomplete: "name" %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-2 offset-3">
      <h5>自己紹介</h5>
    </div>
    <div class="col-3">
      <%= f.text_area :introduction,class: 'form-control',autofocus: true, autocomplete: "introduction" %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-2 offset-3">
      <h5>メールアドレス</h5>
    </div>
    <div class="col-3">
      <%= f.text_field :email,class: 'form-control',autofocus: true, autocomplete: "email" %>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-2 offset-3">
      <h5>退会</h5>
    </div>
    <div class="col-3">
      <%= link_to end_users_confirm_path do %>
         <button type="button" class="btn btn-danger btn-block">退会</button>
      <%end%>
    </div>
  </div>
  <div class="row pb-5">
    <div class="col-2 mx-auto mt-5">
      <%= f.submit "マイページ変更", class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<%end%>

app/views/publics/end_users/show.html.erb
<div class="row">
  <div class="col-auto offset-2 mt-5">
    <h2>マイページ</h2>
  </div>
</div>
<div class="row mt-5">
  <div class="col-2 offset-3">
    <h5>プロフィールアイコン</h5>
  </div>
  <div class="col-3">
    <% if @end_user.image.blank? %>
    　<%= image_tag '/images/default.png' %>
    <%else%>
      <%= attachment_image_tag @end_user, :image, size: "300x200", format: 'jpeg' %>
    <% end %>
  </div>
</div>
<div class="row mt-5">
  <div class="col-2 offset-3">
    <h5>ニックネーム</h5>
  </div>
  <div class="col-3">
    <%= @end_user.name %>
  </div>
</div>
<div class="row mt-5">
  <div class="col-2 offset-3">
    <h5>自己紹介</h5>
  </div>
  <div class="col-3">
    <%= @end_user.introduction %>
  </div>
</div>

<div class="row mt-5">
  <div class="col-2 offset-3">
    <h5>メールアドレス</h5>
  </div>
  <div class="col-3">
    <%= @end_user.email %>
  </div>
</div>
<div class="row mt-5">
  <div class="col-2 offset-3">
    <h5>会員ステータス</h5>
  </div>
  <div class="col-3">
    <% if @end_user.is_deleted == false then %>
      <h6 class="my-auto text-success">有効</h6>
    <%else%>
      <h6 class="my-auto text-dark-50">無効</h6>
    <%end%>
   </div>
</div>
<div class="row mt-5 pb-5">
  <div class="col-2 offset-3">
    <h5>マイページ編集</h5>
  </div>
  <div class="col-3">
    <%= link_to end_users_information_edit_path do %>
      <button type="button" class="btn btn-secondary btn-block">マイページ編集</button>
    <%end%>
  </div>
</div>