config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }
  devise_for :end_users, controllers: {
  sessions:      'publics/sessions',
  passwords:     'publics/passwords',
  registrations: 'publics/registrations'
  }

  scope module: :publics do
    resources :places, only: [:create,:destroy,:show,:edit,:update,:delete]
    patch 'end_users/withdrawal' =>'end_users#withdrawal'
    get 'end_users/mypage' => 'end_users#show'
    get 'end_users/information/edit' => 'end_users#edit'
    patch 'end_users/infomation' => 'end_users#update'
    root 'homes#top'
    resources :groups, only: [:new,:index,:show,:edit,:create]
    post 'groups/add_user' => 'groups#add_user'
    get 'end_users/confirm' => 'end_users#confirm'
    resources :group_users, only:[:destroy]
    # create 'customers/customers/infomation' => 'customers#update'
  end

  namespace :admins do
    resources :end_users, only: [:index,:show,:edit,:update]
    resources :groups, only: [:index,:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  attachment :image
  has_many :group_users
  has_many :end_users, through: :group_users
  has_many :places
  validates :name, presence: true
  validates :introduction, presence: true
  validates :image, presence: true
end

app/controllers/admins/groups_controller.rb
class Admins::GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end
end

app/controllers/publics/confirmations_controller.rb
# frozen_string_literal: true

class Publics::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/publics/end_users_controller.rb
class Publics::EndUsersController < ApplicationController
  def show
    @end_user = current_end_user
  end

  def edit
    @end_user = current_end_user
  end

  def update
    @end_user = EndUser.find(current_end_user.id)
    @end_user.update(end_user_params)
    redirect_to end_users_mypage_path(@end_user)
  end

  def confirm
  end

  def withdrawal
    @end_user = EndUser.find(current_end_user.id)
    @end_user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def end_user_params
    params.require(:end_user).permit(:name,:image,:introduction,:email,:is_deleted)
  end
end

app/controllers/publics/group_users_controller.rb
class Publics::GroupUsersController < ApplicationController
  def destroy
    @group = Group.find(params[:id])
    @end_user = current_end_user
    @group.end_users.delete(current_end_user)
    redirect_to groups_path
  end
end

app/controllers/publics/groups_controller.rb
class Publics::GroupsController < ApplicationController
  def new
    @group = Group.new
  end
  def show
    @group = Group.find(params[:id])
    @place = Place.new
  end

  def index
    @end_user_group_all = current_end_user.groups
    @group_user = GroupUser.new
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    if @group.save
       @group.end_users << current_end_user
      redirect_to group_path(@group), notice: 'グループを作成しました'
    else
      render:new
    end
  end

  def add_user
    @group = Group.find(params[:group_user][:group_id])
    end_user = EndUser.find(params[:group_user][:end_user_id])
    @group.end_users << end_user
    redirect_to group_path(@group), notice: "ユーザーを追加しました。"
  end

  private

  def group_params
    params.require(:group).permit(:name,:introduction,:image,:is_open,:group_id,:end_user_id)
  end
end

app/controllers/publics/homes_controller.rb
class Publics::HomesController < ApplicationController
  def top
  end
end

app/controllers/publics/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Publics::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/publics/passwords_controller.rb
# frozen_string_literal: true

class Publics::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/publics/places_controller.rb
class Publics::PlacesController < ApplicationController
  skip_forgery_protection only: :create
  def create
    @group = Group.find(params[:place][:group_id])
    @place = Place.new(place_params)
    if @place.save
      redirect_to group_path(@group)
    else
      render "publics/groups/show"
    end
  end

  def show
    @place = Place.find(params[:id])
    @group = @place.group_id
  end
  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])
    if @place.update(place_params)
      redirect_to place_path(@place)
    else
      render :edit
    end
  end

  def destroy
    place = Place.find(params[:id])
    group = place.group_id
    place.destroy
    redirect_to group_path(group)
  end

  private
  def place_params
    params.require(:place).permit(:end_user_id, :group_id, :place_name,:address,:introduction,:latitude,:longitude,:image,:number)
  end
end

app/controllers/publics/registrations_controller.rb
# frozen_string_literal: true

class Publics::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  def after_sign_up_path_for(resource)
    end_users_mypage_path
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/publics/sessions_controller.rb
# frozen_string_literal: true

class Publics::SessionsController < Devise::SessionsController

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    test = EndUser.where(email: end_user_params[:email])
    if end_user_params[:email].blank?
      redirect_to new_end_user_session_path, notice: '登録してあるメールアドレスを入力してください'
    elsif end_user_params[:password].blank?
      redirect_to new_end_user_session_path, notice: '登録してあるパスワードを入力してください'
    elsif test[0][:is_deleted] == false
      super
    else
      redirect_to new_end_user_session_path, notice: '退会したアカウントではログインできません'
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(resource)
    end_users_mypage_path
  end

  # protected
  private
    def end_user_params
      params.require(:end_user).permit(:email,:password)
    end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/publics/unlocks_controller.rb
# frozen_string_literal: true

class Publics::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/groups_helper.rb
module Admins::GroupsHelper
end

app/helpers/publics/end_users_helper.rb
module Publics::EndUsersHelper
end

app/helpers/publics/group_users_helper.rb
module Publics::GroupUsersHelper
end

app/helpers/publics/groups_helper.rb
module Publics::GroupsHelper
end

app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

app/helpers/publics/places_helper.rb
module Publics::PlacesHelper
end

app/views/publics/groups/edit.html.erb
<h1>Publics::Groups#edit</h1>
<p>Find me in app/views/publics/groups/edit.html.erb</p>

app/views/publics/groups/index.html.erb
<div class="row">
  <div class="col-auto offset-2 mt-5">
    <h2>所属グループ一覧</h2>
  </div>
</div>
<div class="row mt-5">
  <div class="col-8 mx-auto">

    <table class="table table-bordered border-dark">
      <thead>
        <tr>
          <th class="col-4">グループ名</th>
          <th class="col-5">グループ紹介</th>
          <th class="col-3"></th>
        </tr>
      </thead>
      <tbody>
        <% current_end_user.groups.each do |group| %>
          <tr>
            <td>
              <%= attachment_image_tag group, :image, size: "30x20", format: 'jpeg' %>  <%= group.name %>
            </td>
            <td>
              <%= group.introduction %>
            </td>
            <td>
              <div class="row">
                <div class="col-auto mx-auto">
                  <%= link_to group_path(group) do %>
                    <button type="button" class="btn btn-primary">詳細</button>
                  <%end%>
                </div>
              </div>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-auto offset-2 mt-5">
    <h2>公開グループ一覧</h2>
  </div>
</div>

<div class="row mt-5 mb-5">
  <div class="col-8 mx-auto">
    <table class="table table-bordered border-dark">
      <thead>
        <tr>
          <th class="col-4">グループ名</th>
          <th class="col-5">グループ紹介</th>
          <th class="col-3"></th>
        </tr>
      </thead>
      <tbody>
        <% Group.all.each do |group| %>
          <% if group.is_open == true %>
            <tr>
              <td>
                <%= attachment_image_tag group, :image, size: "30x20", format: 'jpeg' %>  <%= group.name %>
              </td>
              <td>
                <%= group.introduction %>
              </td>
              <td>
                <div class="row">
                  <div class="col-auto mx-auto">
                    <% unless group.end_users.include?(current_end_user) %>
                      <%= form_with model: @group_user, url: groups_add_user_path, method: :POST, local:true do |f| %>
                        <%= f.hidden_field :group_id, value: group.id %>
                        <%= f.hidden_field :end_user_id, value: current_end_user.id %>
                        <%= f.submit "グループ参加", class: 'btn btn-primary btn-block' %>
                      <%end%>
                    <%else%>
                      <div class="row">
                        <div class="col-auto mx-auto">
                          <%= link_to group_path(group) do %>
                             <button type="button" class="btn btn-primary">詳細</button>
                          <%end%>
                        </div>
                      </div>
                    <%end%>
                  </div>
                </div>
              </td>
            </tr>
          <%end%>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/publics/groups/new.html.erb
<% if @group.errors.any? %>
  <%= @group.errors.count %>件のエラーが発生しました
  <% @group.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="row">
  <div class="col-auto offset-2 mt-5">
    <h2>グループ作成</h2>
  </div>
  <div class="col-auto  mt-5">
    <h5 class="text-red">グループ公開を公開するにチェックをすると<br>誰でも自由にグループに参加できるようになります。</h5>
  </div>
</div>
<%= form_with model: @group, url: groups_path(@group), method: :POST, local:true do |f| %>

  <div class="row mt-5">
    <div class="col-2 offset-3">
      <h5>グループアイコン</h5>
    </div>
    <div class="col-3">
      <%= f.attachment_field :image %>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-2 offset-3">
      <h5>グループ名</h5>
    </div>
    <div class="col-3">
      <%= f.text_field :name,class: 'form-control',autofocus: true %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-2 offset-3">
      <h5>グループ紹介</h5>
    </div>
    <div class="col-3">
      <%= f.text_field :introduction,class: 'form-control',autofocus: true %>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-2 offset-3">
      <h5>グループ公開</h5>
    </div>
    <div class="col-3">
      <div class="row">
        <div class="col-auto">
          <%= f.radio_button :is_open, true %>
          <%= f.label :is_open, "公開する" %>
        </div>
        <div class="col-auto">
          <%= f.radio_button :is_open, false %>
          <%= f.label :is_open, "公開しない" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row marginbottom">
    <div class="col-2 mx-auto mt-5">
      <%= f.submit "グループ作成", class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<%end%>

app/views/publics/groups/show.html.erb
<% if @place.errors.any? %>
  <%= @place.errors.count %>件のエラーが発生しました
  <% @place.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="row">
  <div class="col-auto offset-2 mt-5">
    <h2><%= @group.name %></h2>
  </div>
</div>
<div class= "row mt-5">
  <div class="col-8 offset-1">
    <div class="row">
      <div class="col-4">
        <h3>マップ</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-4">
        <input id="address" type="textbox" value="二戸">
        <input type="button" value="場所を検索" onclick="codeAddress()">
        <div id="display">↑☝住所から場所を保存できます。️</div>
      </div>
      <div class="col-auto">
        <%= form_with model: @place, url: places_path, method: :POST, local:true do |f| %>
          <%= f.text_field :latitude, placeholder: "緯度" %>
          <%= f.text_field :longitude, placeholder: "経度" %>
          <%= f.hidden_field :group_id, value: @group.id %>
          <%= f.hidden_field :end_user_id, value: current_end_user.id %>
          <%= f.hidden_field :address, id: "addressOutput" %>
          <%= f.submit '緯度と経度で登録する', class: 'btn btn-primary' %>
        <%end%>
      </div>
    </div>
    <div class="map">
      <div id="map">
      </div>
    </div>
  </div>

  <div class="col-3 mt-5">
    <div class="row mt-5">
      <div class="col-auto">
        <h3>
          現在地登録フォーム
        </h3>
      </div>
    </div>
    <%= form_with model: @place, url: places_path, method: :POST, local:true do |f| %>
　    <div class="row mt-1">
        <div class="col-auto">
          <h4>
            画像選択
          </h4>
        </div>
      </div>
      <div class="row mt-1">
        <div class="col-11">
          <%= f.attachment_field :image %>
        </div>
      </div>
　    <div class="row mt-1">
        <div class="col-auto">
          <h4>
            場所名
          </h4>
        </div>
      </div>
      <div class="row">
        <div class="col-11">
          <%=f.text_field :place_name, class: "form-control",autofocus: true %>
        </div>
      </div>
      <div class="row mt-3">
        <div class="col-auto">
          <h4>
            場所説明
          </h4>
        </div>
      </div>
      <div class="row">
        <div class="col-11">
          <%=f.text_area :introduction, class: "form-control",autofocus: true %>
        </div>
      </div>
      <%= f.hidden_field :group_id, value: @group.id %>
      <%= f.hidden_field :end_user_id, value: current_end_user.id %>
      <%= f.hidden_field :latitude, id: "latitude" %>
      <%= f.hidden_field :longitude, id: "longitude" %>
      <%= f.hidden_field :address, id: "add" %>
      <%= f.submit '現在地を登録する', class: 'btn btn-primary mt-3' %>
    <%end%>
  </div>
</div>


<div type="text/javascript">
  <script>
    let map
    let geocoder
    // 下の1行を追加
    const display = document.getElementById('display')
    function initMap(){
       geocoder = new google.maps.Geocoder()
       map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: 40.271104, lng: 141.305063},
        zoom: 10,
      });
      <% @group.places.each do |place| %>
        map.setCenter( new google.maps.LatLng( <%= place.latitude %>, <%= place.longitude %> ) ) ;
        var marker = null;
        var infoWindow = null;
      　marker = new google.maps.Marker({
        　position:  {lat: <%= place.latitude %>, lng: <%= place.longitude %>},
        　map: map
    　　});

        infoWindow = new google.maps.InfoWindow({
          content: '<%= attachment_image_tag place, :image, format: 'jpeg', size: "250x170" %><br>地点名 : <%= place.place_name %><br>住所 : <%= place.address %><br>地点説明：<%= place.introduction %> <br>本数：<%= place.number %>本；<br>登録ユーザー : <%= place.end_user.name %><br><%= link_to place_path(place) do %><button type="button" class="btn btn-primary">詳細</button><%end%>'
        });
        infoWindowOpen(marker,infoWindow);
      <%end%>
      function infoWindowOpen(marker,infoWindow){
        marker.addListener('click', function(){
          infoWindow.open(map, marker);
        });
      }
    }
    function codeAddress(){
      var geocoder = new google.maps.Geocoder();

      let inputAddress = document.getElementById('address').value;

      geocoder.geocode( { 'address': inputAddress}, function(results, status) {
        if (status == 'OK') {
          map.setCenter(results[0].geometry.location);
          const marker = new google.maps.Marker({
              map: map,
              position: results[0].geometry.location
          });
          const infoWindow = new google.maps.InfoWindow({
            content:'<form action="/places" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓">'
              +'<input type="hidden" name="place[end_user_id]" id="place_end_user_id_in_info_window" value=' + document.getElementById('place_end_user_id').value + '>'
              +'<input type="hidden" name="place[group_id]" id="place_gruop_id_in_info_window" value=' + document.getElementById('place_group_id').value + '>'
              +'<input id="lat_address" type="hidden" name="place[latitude]" value=' + results[ 0 ].geometry.location.lat() + '>'
              +'<input id="lng_address" type="hidden" name="place[longitude]" value=' + results[ 0 ].geometry.location.lng() + '>'
              +'<input id="address_address" type="hidden" name="place[address]" value=' + document.getElementById('address').value + '>'
              +'<input type="submit" name="commit" value="場所を登録する" class="btn btn-primary" data-disable-with="場所を登録する">'
            +'</form>'
          });
          marker.addListener('click', function(){
            infoWindow.open(map, marker);
          });
          display.textContent = "検索結果：" + results[ 0 ].geometry.location
        } else {
          alert('該当する結果がありませんでした：' + status);
        }
      });
    }
  if( navigator.geolocation )
  {
  	// 現在地を取得
  	navigator.geolocation.getCurrentPosition(
  		// [第1引数] 取得に成功した場合の関数
  		function( position )
  		{
  			// 取得したデータの整理
  			var data = position.coords ;
  			// データの整理
  			var lat = data.latitude ;
  			var lng = data.longitude ;
  			var alt = data.altitude ;
  		 	var accLatlng = data.accuracy ;
  		 	var accAlt = data.altitudeAccuracy ;
  			var heading = data.heading ;			//0=北,90=東,180=南,270=西
  			var speed = data.speed ;
  			var Address ;
        (function(){
          var requestAjax = function(endpoint, callback) {
            var xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function(){
              if (this.readyState==4 && this.status==200) {
                callback(this.response);
              }
            };
            xhr.responseType = 'json';
            xhr.open('GET',endpoint,true);
            xhr.send();
          };
          // 東京駅の緯度経度
          var apiKey = '<%= ENV['API_KEY'] %>';
          var requestURL = 'https://maps.googleapis.com/maps/api/geocode/json?language=ja&sensor=false';
          requestURL += '&latlng=' + lat + ',' + lng;
          requestURL += '&key=' + apiKey;
          console.log(requestURL);
          requestAjax(requestURL, function(response){
            if (response.error_message) {
              console.log(response.error_message);
            } else {
              Address = response.results[0]['formatted_address'];
              // 住所は「日本、〒100-0005 東京都千代田区丸の内一丁目」の形式
              console.log(Address);
              // var data = formattedAddress.split(' ');
              // console.log(data);
              document.getElementById("add").value = Address;
            }
          });
        })();
        document.getElementById("latitude").value = lat;
        document.getElementById("longitude").value = lng;
        alert( "あなたの現在位置は、\n[" + lat + "," + lng + "]\nです。" ) ;
  		},
  		function( error )
  		{
  			// エラーコード(error.code)の番号
  			// 0:UNKNOWN_ERROR				原因不明のエラー
  			// 1:PERMISSION_DENIED			利用者が位置情報の取得を許可しなかった
  			// 2:POSITION_UNAVAILABLE		電波状況などで位置情報が取得できなかった
  			// 3:TIMEOUT					位置情報の取得に時間がかかり過ぎた…
  			// エラー番号に対応したメッセージ
  			var errorInfo = [
  				"原因不明のエラーが発生しました…。" ,
  				"位置情報の取得が許可されませんでした…。" ,
  				"電波状況などで位置情報が取得できませんでした…。" ,
  				"位置情報の取得に時間がかかり過ぎてタイムアウトしました…。"
  			] ;
  			// エラー番号
  			var errorNo = error.code ;

  			// エラーメッセージ
  			var errorMessage = "[エラー番号: " + errorNo + "]\n" + errorInfo[ errorNo ] ;

  			// アラート表示
  			alert( errorMessage ) ;

  			// HTMLに書き出し
  			document.getElementById("result").innerHTML = errorMessage;
  		} ,

  		// [第3引数] オプション
  		{
  			"enableHighAccuracy": false,
  			"timeout": 8000,
  			"maximumAge": 2000,
    	}
    	) ;
  }
    // 対応していない場合
  else
  {
    	// エラーメッセージ
    	var errorMessage = "お使いの端末は、GeoLacation APIに対応していません。" ;

    	// アラート表示
    	alert( errorMessage ) ;

    	// HTMLに書き出し
    	document.getElementById( 'result' ).innerHTML = errorMessage ;
  }
  //   )
  // }
  </script>
　<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&callback=initMap" async defer></script>
</div>

<div class="row">
  <div class="col-auto offset-2">
    <h3>保存した場所</h3>
  </div>
</div>
<div class="row mt-2">
  <div class="col-8 mx-auto">
    <table class="table table-bordered border-dark">
      <thead>
        <tr>
          <th class="col-2">場所名</th>
          <th class="col-1">本数</th>
          <th class="col-5">場所説明</th>
          <th class="col-4"></th>
        </tr>
      </thead>
      <tbody>
        <% @group.places.each do |place| %>
          <tr>
            <td>
              <%= attachment_image_tag place, :image, size: "30x20", format: 'jpeg' %>  <%= place.place_name%>
            </td>
            <td>
              <%= place.number %>
            </td>
            <td>
              <%= place.introduction %>
            </td>
            <td>
              <div class="row">
                <div class="col-auto">
                  <%= link_to place_path(place) do %>
                    <button type="button" class="btn btn-primary">場所詳細</button>
                  <%end%>
                </div>
                <div class="col-auto">
                  <%= link_to edit_place_path(place) do %>
                    <button type="button" class="btn btn-success">場所編集</button>
                  <%end%>
                </div>
              </div>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>
<div class="row mt-5">
  <div class="col-8 mx-auto">
    <table class="table table-bordered border-dark">
      <thead>
        <tr>
          <th class="col-4">所属メンバー</th>
          <th class="col-5">メンバー紹介</th>
          <th class="col-3"></th>
        </tr>
      </thead>
      <tbody>
        <% @group.end_users.each do |group_user| %>
          <tr>
            <td>
              <%= attachment_image_tag group_user, :image, size: "30x20", format: 'jpeg' %>  <%= group_user.name%>
            </td>
            <td>
              <%= group_user.introduction %>
            </td>
            <td>
              <% if group_user == current_end_user %>
                <%= link_to "グループ退会",group_user_path(@group), class: "btn btn-block btn-danger", method: :DELETE, data: {confirm: "退会しますか？"} %>
              <%end%>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>