config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }
  devise_for :end_users, controllers: {
  sessions:      'publics/sessions',
  passwords:     'publics/passwords',
  registrations: 'publics/registrations'
  }

  scope module: :publics do
    resources :places, only: [:create,:destroy,:show,:edit,:update,:delete]
    patch 'end_users/withdrawal' =>'end_users#withdrawal'
    get 'end_users/mypage' => 'end_users#show'
    get 'end_users/information/edit' => 'end_users#edit'
    patch 'end_users/infomation' => 'end_users#update'
    root 'homes#top'
    resources :groups, only: [:new,:index,:show,:edit,:create]
    post 'groups/add_user' => 'groups#add_user'
    get 'end_users/confirm' => 'end_users#confirm'
    resources :group_users, only:[:destroy]
    # create 'customers/customers/infomation' => 'customers#update'
  end

  namespace :admins do
    resources :end_users, only: [:index,:show,:edit,:update]
    resources :groups, only: [:index,:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
  # mount_uploader :image, ImageUploader
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :places

  # validates :name, presence: true
  # validates :introduction, presence: true
  # validates :image_id, presence: true
  # validates :is_deleted, presence: true
  validates :email, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  attachment :image
  has_many :group_users
  has_many :end_users, through: :group_users
  has_many :places
  validates :name, presence: true
  validates :introduction, presence: true
  validates :image, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :end_user, dependent: :destroy
  belongs_to :group
  validates :end_user, presence: true
  validates :group, presence: true
end

app/models/place.rb
class Place < ApplicationRecord
  attachment :image
  belongs_to :end_user
  belongs_to :group
  validates :latitude, presence: true
  validates :longitude, presence: true
end

app/controllers/admins/groups_controller.rb
class Admins::GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/publics/groups_controller.rb
class Publics::GroupsController < ApplicationController
  def new
    @group = Group.new
  end
  def show
    @group = Group.find(params[:id])
    @place = Place.new
  end

  def index
    @end_user_group_all = current_end_user.groups
    @group_user = GroupUser.new
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    if @group.save
       @group.end_users << current_end_user
      redirect_to group_path(@group), notice: 'グループを作成しました'
    else
      render:new
    end
  end

  def add_user
    @group = Group.find(params[:group_user][:group_id])
    end_user = EndUser.find(params[:group_user][:end_user_id])
    @group.end_users << end_user
    redirect_to group_path(@group), notice: "ユーザーを追加しました。"
  end

  private

  def group_params
    params.require(:group).permit(:name,:introduction,:image,:is_open,:group_id,:end_user_id)
  end
end

app/controllers/publics/homes_controller.rb
class Publics::HomesController < ApplicationController
  def top
  end
end

app/controllers/publics/places_controller.rb
class Publics::PlacesController < ApplicationController
  skip_forgery_protection only: :create
  def create
    @group = Group.find(params[:place][:group_id])
    @place = Place.new(place_params)
    if @place.save
      redirect_to group_path(@group)
    else
      render "publics/groups/show"
    end
  end

  def show
    @place = Place.find(params[:id])
    @group = @place.group_id
  end
  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])
    if @place.update(place_params)
      redirect_to place_path(@place)
    else
      render :edit
    end
  end

  def destroy
    place = Place.find(params[:id])
    group = place.group_id
    place.destroy
    redirect_to group_path(group)
  end

  private
  def place_params
    params.require(:place).permit(:end_user_id, :group_id, :place_name,:address,:introduction,:latitude,:longitude,:image,:number)
  end
end

app/helpers/admins/end_users_helper.rb
module Admins::EndUsersHelper
end

app/helpers/admins/groups_helper.rb
module Admins::GroupsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publics/end_users_helper.rb
module Publics::EndUsersHelper
end

app/helpers/publics/group_users_helper.rb
module Publics::GroupUsersHelper
end

app/helpers/publics/groups_helper.rb
module Publics::GroupsHelper
end

app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

app/helpers/publics/places_helper.rb
module Publics::PlacesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrushiMap2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-height">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <div class="row height_100">
        <div class="col-auto my-auto ml-auto">
          <%= link_to root_path do %>
            <h2>漆マップ(テスト)</h2>
          <%end%>
        </div>
        <% if end_user_signed_in? %>
          <div class="col-auto my-auto ml-auto">
            <%= link_to new_group_path do %>
              <button type="button" class="btn btn-secondary">グループ作成</button>
            <%end%>
          </div>
          <div class="col-auto my-auto">
            <%= link_to end_users_mypage_path do %>
              <button type="button" class="btn btn-secondary">マイページ編集</button>
            <%end%>
          </div>

          <div class="col-auto my-auto">
            <%= link_to groups_path do %>
              <button type="button" class="btn btn-secondary">グループ一覧</button>
            <%end%>
          </div>
          <div class="col-auto my-auto mr-5">
            <%= link_to destroy_end_user_session_path, method: :delete do %>
              <button type="button" class="btn btn-secondary">ログアウト</button>
            <%end%>
          </div>
        <%elsif admin_signed_in? %>
          <div class="col-auto my-auto ml-auto">
            <%= link_to  admins_end_users_path do %>
              <button type="button" class="btn btn-secondary">会員一覧</button>
            <%end%>
          </div>

         <div class="col-auto my-auto">
            <%= link_to  admins_groups_path do %>
              <button type="button" class="btn btn-secondary">グループ一覧</button>
            <%end%>
          </div>

          <div class="col-auto my-auto mr-5">
            <%= link_to destroy_admin_session_path, method: :delete do %>
               <button type="button" class="btn btn-secondary">ログアウト</button>
            <%end%>
          </div>
        <%else%>
          <div class="col-auto my-auto ml-auto">
            <%= link_to new_end_user_registration_path do %>
              <button type="button" class="btn btn-secondary">会員登録</button>
            <%end%>
          </div>
          <div class="col-auto my-auto mr-5">
            <%= link_to new_end_user_session_path do %>
              <button type="button" class="btn btn-secondary">ログイン</button>
            <%end%>
          </div>
        <%end%>
      </div>
    </header>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
    <footer>
    </footer>
  </body>
</html>